CREATE TABLE Word (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  value TEXT NOT NULL,
  language TEXT NOT NULL
);

CREATE TABLE _Pair (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  aId INTEGER NOT NULL,
  bId INTEGER NOT NULL,
  FOREIGN KEY(aId) REFERENCES Word(id),
  FOREIGN KEY(bId) REFERENCES Word(id)
);

CREATE TABLE Category (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE _PairCategory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pairId INTEGER NOT NULL,
  categoryId INTEGER NOT NULL,
  FOREIGN KEY(pairId) REFERENCES _Pair(id),
  FOREIGN KEY(categoryId) REFERENCES Category(id)
);
